routes:
  /books/:
    controller: channel
    filter: tag:books
    template: books

  /projects/:
    controller: channel
    filter: tag:projects
    template: projects

  /goals/:
    controller: channel
    filter: tag:goals
    template: goals

  /series/python-like-a-pro/:
    controller: channel
    filter: tag:python-like-pro
    template: series/python-like-pro

  /series/antifragile-dev/:
    controller: channel
    filter: tag:antifragile-dev
    template: series/antifragile-dev

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
